[package]
name = "raph-rs"
version = "0.1.0"
authors = ["AstolfoDev <no-reply@astolfo.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.1"
tokio = { version = "0.2", features = ["macros"] }